name: build
on:
  push:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  statuses: write

jobs:
  run:
    name: build
    strategy:
      matrix:
        os:
          - ubuntu-latest
            #- windows-latest   # see  https://github.com/ocaml/setup-ocaml/issues/361
            #- macos-latest  # clogs CI
        ocaml-compiler:
          - '4.08.0'
          - '5.0.0'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: ./.github/actions/slack-send-build-status/
      with:
        slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
        allow-prerelease-opam: true
    - run: opam pin -n .
    - run: opam depext -yt cbor-pack cbor-pack-ppx
    - run: opam install -t . --deps-only
    - run: opam exec -- dune build --ignore-promoted-rules
    - run: opam exec -- dune runtest --ignore-promoted-rules
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.ocaml-compiler == '5.0.0' }}
